# Introduction to NumPy

## Row vector:
$ \begin{bmatrix} 1 & 2 \end{bmatrix} $

## Column vector:
$ \begin{bmatrix} 3 \\ 4 \end{bmatrix} $

## Square matrix:
$ \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $

In [1]:
1 + 3

4

In [2]:
import numpy as np
np.array([3, 4, 5]) # 1D array

array([3, 4, 5])

In [3]:
w = np.array([10, 15])

In [4]:
w

array([10, 15])

## Check dimension of an array

In [5]:
w.shape # use .shape to view the attribute (dimension) of the array

(2,)

In [6]:
w = np.array([[1, 2, 3]])
w

array([[1, 2, 3]])

In [7]:
w.shape

(1, 3)

In [8]:
w.T

array([[1],
       [2],
       [3]])

In [9]:
w.T.shape

(3, 1)

### this is cool, can also be done by .dot() method 

In [11]:
w @ w.T

array([[14]])

In [12]:
np.dot(w, w.T)

array([[14]])

In [16]:
w.T @ w   # usually use this one 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [17]:
np.matmul(w, w.T)  # order matters 

array([[14]])

### Checking shape 

In [18]:
M = np.array([[1,2], [3,4]])  # two brackets 
M

array([[1, 2],
       [3, 4]])

In [19]:
M.shape

(2, 2)

In [21]:
w = np.array([[0.2, 0.8]])   # weight 
print(w.shape)
S = np.array([[0.3, 0.25],    # var-cov matrix 
              [0.25, 0.4]])

w @ S

(1, 2)


array([[0.26, 0.37]])

In [22]:
w @ S @ w.T

array([[0.348]])

In [26]:

w @ S @ w      # without transpose, we get direct answer 

0.3480000000000001

### Checking the variables 

In [27]:
whos

Variable   Type       Data/Info
-------------------------------
M          ndarray    2x2: 4 elems, type `int64`, 32 bytes
S          ndarray    2x2: 4 elems, type `float64`, 32 bytes
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
w          ndarray    2: 2 elems, type `float64`, 16 bytes


In [40]:
# compare the following 

X = np.array([1, 2])
Y = np.array([[1, 2]])
print(X.shape)
print(Y.shape)


(2,)
(1, 2)


In [51]:
Y1= Y.T
Y1.shape 

(2, 1)

In [36]:
Y = np.array([[3], [4]])
Y

array([[3],
       [4]])

In [37]:
Y.shape

(2, 1)

In [38]:
np.eye(2) # identity matrix

array([[1., 0.],
       [0., 1.]])

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [59]:
zero1 = np.zeros((1, 2))
zero1.shape


(1, 2)

In [60]:
zero2 = np.array([0.0, 0.0])
zero2.shape  

(2,)

### def an utitlity function to do constraints optimization 

In [52]:
def util(x, y):
    return x*y 

In [53]:
util(2, 3)

6

### only one variable

In [54]:
# with array 

def u(x):
    util = x[0] * x[1]
    return util

u(np.array([2, 3]))

6

### Optimizer ( minimizer)
- fsolve method 
    - Purpose: It is used for finding the roots (solutions) of a system of nonlinear equations. 
    - It solves the equation f(x) = 0.


In [67]:
from scipy.optimize import minimize # optimizers

def u(x):  # turn a max problem into a min one
    util = -(x[0] * x[1])  # utility function: U = x[0] * x[1] 
    return util

x0 = np.array([0.0, 0.0]) # initial guess

# Constraints func 
eq_constraints = {'type': 'eq', 'fun' : lambda x: np.array([1*x[0] + 2*x[1] - 120])}  # x[0] + 2*x[1] = 120 --> cost function 

""" 
eq: equality ( which the contraint will exist a = , instead of > or < )
    - inequality ( < or > )
fun: 
    - Defines the constraint function as a lambda function.
    - The function takes an array x as input and returns the result of the equation 1*x[0] + 2*x[1] - 120.
"""




result = minimize(u, x0, method='SLSQP',    # method : solver 
               constraints=eq_constraints,
               options={'ftol': 1e-20, 'disp': True})   # options : result in deccimal places, display  = True 
result.x

Optimization terminated successfully    (Exit mode 0)
            Current function value: -1799.999999999998
            Iterations: 6
            Function evaluations: 18
            Gradient evaluations: 6


array([60.00000191, 29.99999905])

In [65]:
-result.fun

# the correct answer ( since we took neg in the beginning for minimization )
# the result of this is : utility function ( x y)

1799.999999999998

""" 


In [68]:
x0 = np.array([120, 0])
res = minimize(u, x0, method='SLSQP',
               constraints=eq_constraints,
               options={'ftol': 1e-9, 'disp': True})
res.x

Optimization terminated successfully    (Exit mode 0)
            Current function value: -1800.0000000000005
            Iterations: 3
            Function evaluations: 9
            Gradient evaluations: 3


array([60., 30.])